CarService/CarService.Web/ViewModels/Home/OrderItem.cs
namespace CarService.Web.ViewModels.Home
{
    public class OrderItem
    {
        public int OrderId { get; set; }
        public int CustomerId { get; set; }
        public string Customer { get; set; }
        public string Car { get; set; }
        public string OrderType { get; set; }
        public string OrderStatus { get; set; }
        public int EmployeeId { get; set; }
        public string Employee { get; set; }
    }
}

CarService/CarService.Web/ViewModels/Home/StartPageViewModel.cs
using System.Collections.Generic;

namespace CarService.Web.ViewModels.Home
{
    public class StartPageViewModel
    {
        public string UserName { get; set; }
        public bool IsVerified { get; set; }
        public IEnumerable<OrderItem> OrderItems { get; set; }
    }
}

CarService/CarService.Web/Controllers/Car/CarController.cs
using CarService.Web.Services.Car;
using CarService.Web.Services.Customer;
using System.Web.Mvc;

namespace CarService.Web.Controllers.Car
{
    public partial class CarController : Controller
    {
        private readonly ICustomerService _customerService;
        private readonly ICarsService _carService; 
        
        public CarController(ICustomerService customerService,
            ICarsService carService)
        {
            _customerService = customerService;
            _carService = carService;
        }
    }
}

CarService/CarService.Web/Controllers/HomeController.cs
using CarService.Web.Services.Employee;
using CarService.Web.Services.Order;
using CarService.Web.ViewModels.Home;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web.Mvc;

namespace CarService.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IEmployeeService _employeeService;
        private readonly IOrderService _orderService;
        
        public HomeController(IEmployeeService empoloyeeService,
            IOrderService orderService)
        {
            _employeeService = empoloyeeService;
            _orderService = orderService;
        }
        //[HttpGet, Route("Home")]
        public ActionResult Index()
        {
            var identity = (ClaimsIdentity)User.Identity;
            IEnumerable<Claim> claims = identity.Claims;
            var userId = int.Parse(claims.Where(x => x.Type == "Id").Select(w => w.Value).FirstOrDefault());

            var viewModel = new StartPageViewModel
            {
                UserName = User.Identity.Name,
                IsVerified = _employeeService.Employees.Where(x => x.User_Id == userId && x.IsActive).FirstOrDefault().IsVerified,
                OrderItems = _orderService.Orders.OrderByDescending(x => x.ModifyDate).Take(6).Select(n => new OrderItem
                {
                    OrderId = n.Id,
                    CustomerId = n.Customer.Id,
                    Customer = string.Format("{0} {1}", n.Customer.Name, n.Customer.Surname),
                    Car = string.Format("{0} {1}", n.Car.Mark, n.Car.Model),
                    OrderType = n.OrderType.Name,
                    OrderStatus = n.OrderStatus.Name,
                    EmployeeId = n.Employee.Id,
                    Employee = string.Format("{0} {1}", n.Employee.Name, n.Employee.Surname)
                })
            };
            return View(viewModel);
        }
    }
}

CarService/CarService.Web/Controllers/Order/OrderController.cs
using CarService.Web.Services.Car;
using CarService.Web.Services.Cost;
using CarService.Web.Services.Employee;
using CarService.Web.Services.Order;
using System.Web.Mvc;

namespace CarService.Web.Controllers.Order
{
    public partial class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly ICarsService _carService;
        private readonly IEmployeeService _employeeService;
        private readonly ICostService _costService;

        public OrderController(IOrderService orderService,
            ICarsService carService,
            IEmployeeService employeeService,
            ICostService costService)
        {
            _orderService = orderService;
            _carService = carService;
            _employeeService = employeeService;
            _costService = costService;
        }
    }
}

CarService/CarService.Web/Views/Home/Index.cshtml
@model CarService.Web.ViewModels.Home.StartPageViewModel

@if (!Model.IsVerified)
{
    <div class="alert alert-info text-center">Uzupełnij swój profil pracownika</div>
}
<div class="container">
    @*<hr />*@<br />
    <div class="row">
        <div class="col-md-9">
            <div class="panel panel-primary" style="border-radius: 0px;">
                <div class="panel-heading clearfix" style="padding: 6px 6px 6px 6px; border-radius:0px;">
                    <h4 class="panel-title pull-left" style="padding-top:5px; ">Ostatnio modyfikowane</h4>
                </div>
                <div class="panel-body" style="padding: 0; margin-bottom:-20px;">
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Nr. zl.</th>
                                <th>Klient</th>
                                <th>Samochód</th>
                                <th>Typ</th>
                                <th>Status</th>
                                <th>Pracownik</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.OrderItems)
                            {
                                <tr>
                                    <td><a href="@Url.Action("Edit", "Order", new { id = item.OrderId})">@item.OrderId</a></td>
                                    <td><a href="@Url.Action("Edit", "Customer", new { id = item.CustomerId, returnUrl = HttpContext.Current.Request.Url })">@item.Customer</a></td>
                                    <td>@item.Car</td>
                                    <td>@item.OrderType</td>
                                    <td>@item.OrderStatus</td>
                                    <td>@item.Employee</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="panel panel-primary" style="border-radius: 0px;">
                <div class="panel-heading clearfix" style="padding: 6px 6px 6px 6px; border-radius:0px;">
                    <h4 class="panel-title pull-left" style="padding-top:5px; ">Szybkie dodawanie</h4>
                </div>
                <div class="panel-body" style="margin-bottom:-15px; margin-top:-15px;">
                    <div class="row">
                        <a href="@Url.Action("Create", "Order", new { returnUrl = HttpContext.Current.Request.Url })" class="btn btn-default btn-block" style="border-radius:0px; border-color:#6e80e7">Nowe zlecenie</a>
                    </div>
                    <div class="row">
                        <a href="@Url.Action("Create", "Customer", new { returnUrl = HttpContext.Current.Request.Url })" class="btn btn-default btn-block" style="border-radius:0px; border-color:#6e80e7">Nowy klient</a>
                    </div>
                    <div class="row">
                        <a href="@Url.Action("Create", "Car", new { returnUrl = HttpContext.Current.Request.Url })" class="btn btn-default btn-block" style="border-radius:0px; border-color:#6e80e7">Nowy samochód</a>
                    </div>
                    @if (User.IsInRole("Admin"))
                    {
                        <div class="row">
                            <a href="@Url.Action("Create", "Employee", new { returnUrl = HttpContext.Current.Request.Url })" class="btn btn-default btn-block" style="border-radius:0px; border-color:#6e80e7">Nowy pracownik</a>
                        </div>
                    }
                </div>
            </div>

            @*<div class="panel panel-body panel-default" style="border-radius: 0px;">
                <div class="panel-heading" style="background-color:white; padding: 0; margin-top:-15px;">
                    <h4>Dodaj naprawę</h4>
                </div>
                <div class="row">
                    <button type="button" class="btn btn-default btn-block" style="border-radius:0px;">Hej</button>
                </div>
                <div class="row">
                    <button type="button" class="btn btn-default btn-block" style="border-radius:0px;">sdfsdf</button>
                </div>
                <div class="row">
                    <button type="button" class="btn btn-default btn-block" style="border-radius:0px;">Hedsfsdfj</button>
                </div>
            </div>*@
        </div>
    </div>
</div>