CarService/CarService.Web/ViewModels/Customer/Edit.cs
using CarService.Web.ViewModels.Car;
using System.Collections.Generic;

namespace CarService.Web.ViewModels.Customer
{
    public class Edit
    {
        public CustomerEdit Customer { get; set; }
        public IEnumerable<CarItem> Cars { get; set; }
    }
}

CarService/CarService.Web/ViewModels/Employee/Create.cs
using CarService.Web.Mvc.Other;
using CarService.Web.ViewModels.Shared.Address;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarService.Web.ViewModels.Employee
{
    public class Create : IValidatableObject
    {
        [DisplayName("Imię"), Required(ErrorMessage = "Imię jest wymagane")]
        public string Name { get; set; }

        [DisplayName("Nazwisko"), Required(ErrorMessage = "Nazwisko jest wymagane")]
        public string Surname { get; set; }

        [DisplayName("PESEL"), Required(ErrorMessage = "Pesel jest wymagany")]
        public string Pesel { get; set; }

        [Phone]
        [DisplayName("Telefon")]
        public string Phone { get; set; }

        [DisplayName("Email"), Required(ErrorMessage = "Email jest wymagany")]
        [EmailAddress]
        public string Email { get; set; }

        [DisplayName("Data urodzenia"), Required(ErrorMessage = "Data urodzenia jest wymagana")]
        [DataType(DataType.Date)]
        public DateTime BirthDate { get; set; }

        [DisplayName("Pensja")]
        public decimal? Salary { get; set; }

        [DisplayName("Stanowisko")]
        public int PositionId { get; set; }
        public IEnumerable<SelectListItem> Positions { get; set; }

        public bool IsAdministrator { get; set; }

        public AddressEdit AddressEdit { get; set; }

        public string ReturnUrl { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (IsValidBirthDay())
            {
                yield return new ValidationResult("Musisz mieć ukończone 18 lat", new[] { "BirthDate" });
            }
        }

        private bool IsValidBirthDay()
        {
            const long AgeOfAdult = 567648000000;

            var dt1900 = new DateTime(1900, 1, 1);
            var current = DateTime.Now;
            var spanCurrent = current - dt1900;
            var spanDateOfBirth = BirthDate - dt1900;

            var span = spanCurrent - spanDateOfBirth;
            return span.TotalMilliseconds < AgeOfAdult;
        }

        public Data.Models.User ToUser()
        {
            return new Data.Models.User
            {
                CreateDate = DateTime.Now,
                ModifyDate = DateTime.Now,
                IsActive = true,
                DateofBirth = BirthDate,
                Email = Email,
                Name = Name,
                Surname = Surname,
                Role_Id = IsAdministrator ? (int)Data.Enums.Role.Admin : (int)Data.Enums.Role.Employee,
                Password = Encrypt.EncryptPassword("qwerty1")
            };
        }

        public Data.Models.Employee ToEmployee(Data.Models.User user)
        {
            return new Data.Models.Employee
            {
                CreateDate = DateTime.Now,
                ModifyDate = DateTime.Now,
                IsActive = true,
                IsVerified = true,
                Name = Name,
                Surname = Surname,
                Pesel = Pesel,
                Phone = Phone,
                Position_Id = PositionId,
                Salary = Salary ?? 0,
                Address = AddressEdit.ToNewAddress(),
                User = user
            };
        }
    }
}

CarService/CarService.Web/ViewModels/Employee/EmployeeEdit.cs
using CarService.Web.ViewModels.Order;
using CarService.Web.ViewModels.Shared.Address;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace CarService.Web.ViewModels.Employee
{
    public class EmployeeEdit
    {
        public int Id { get; set; }

        [DisplayName("Imię")]
        [Required(ErrorMessage ="Pole Imię jest wymagane")]
        public string Name { get; set; }

        [DisplayName("Nazwisko")]
        [Required(ErrorMessage = "Pole Nazwisko jest wymagane")]
        public string Surname { get; set; }

        [DisplayName("Pesel")]
        [Required(ErrorMessage = "Pole Pesel jest wymagane")]
        public string Pesel{ get; set; }

        [DisplayName("Telefon")]
        [Required(ErrorMessage = "Pole Telefon jest wymagane")]
        public string Phone{ get; set; }

        [DisplayName("Stanowisko")]
        [Required(ErrorMessage = "Pole Stanowisko jest wymagane")]
        public int PositionId{ get; set; }
        public IEnumerable<SelectListItem> Positions { get; set; }

        [DisplayName("Pensja")]
        public decimal? Salary { get; set; }

        public bool EmployeeIsAdministrator{ get; set; }

        public bool IsAdmin { get; set; }

        public AddressEdit AddressEdit { get; set; }

        public IEnumerable<OrderList> OrderList { get; set; }

        private readonly Data.Models.Employee _employee;
        
        public EmployeeEdit(Data.Models.Employee employee)
        {
            _employee = employee;

            Id = employee.Id;
            Name = employee.Name;
            Surname = employee.Surname;
            Pesel = employee.Pesel;
            Phone = employee.Phone;
            AddressEdit = new AddressEdit(employee.Address);
            Salary = employee.Salary;
            EmployeeIsAdministrator = employee.User.Role.Id == (int)Data.Enums.Role.Admin;
            if (employee.Position != null)
                PositionId = employee.Position.Id;
            
        }

        public Data.Models.Employee ToEmployee()
        {
            _employee.ModifyDate = DateTime.Now;
            _employee.Name = Name;
            _employee.Surname = Surname;
            _employee.Pesel = Pesel;
            _employee.Phone = Phone;
            if (IsAdmin)
            {
                _employee.Salary = Salary ?? 0;
                _employee.User.Role_Id = EmployeeIsAdministrator ? (int)Data.Enums.Role.Admin : (int)Data.Enums.Role.Employee;
            }
            if (_employee.Position == null)
                _employee.Position = new Data.Models.Position { Id = PositionId };
            _employee.Address = _employee.Address == null ? AddressEdit.ToNewAddress() : AddressEdit.ToAddress();
            if (!_employee.IsVerified)
                _employee.IsVerified = true;

            return _employee;
        }
    }
}

CarService/CarService.Web/ViewModels/Employee/EmployeeSearchItem.cs
using PagedList;
using System.Collections.Generic;
using System.ComponentModel;
using System.Web.Mvc;

namespace CarService.Web.ViewModels.Employee
{
    public class EmployeeSearchItem
    {
        public int AuthenticatedUserId { get; set; }

        [DisplayName("Imię")]
        public string Name { get; set; }

        [DisplayName("Nazwisko")]
        public string Surname { get; set; }

        [DisplayName("E-mail")]
        public string Email { get; set; }

        [DisplayName("Stanowisko")]
        public int? PositionId { get; set; }
        public IEnumerable<SelectListItem> Positions { get; set; }

        public IPagedList<ResultItem> ResultItems { get; set; }
    }
}

CarService/CarService.Web/ViewModels/Employee/ResultItem.cs
namespace CarService.Web.ViewModels.Employee
{
    public class ResultItem
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Position { get; set; }
        public int CountOfTasks { get; set; }
    }
}

CarService/CarService.Web/ViewModels/Employee/Schedule.cs
using System;

namespace CarService.Web.ViewModels.Employee
{
    public class Schedule
    {
        public int OrderId { get; set; }
        public string CreateDate { get; set; }
        public string CustomerName { get; set; }
        public string Car { get; set; }
        public string OrderStatus { get; set; }
    }
}

CarService/CarService.Web/ViewModels/Order/Create.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace CarService.Web.ViewModels.Order
{
    public class Create
    {
        [DisplayName("Wybierz klienta"), Required(ErrorMessage = "Wybór klienta jest wymagany")]
        public int CustomerId { get; set; }
        public IEnumerable<SelectListItem> Customers { get; set; }

        [DisplayName("Typ"), Required(ErrorMessage = "Typ zlecenia jest wymagany")]
        public int OrderTypeId { get; set; }
        public IEnumerable<SelectListItem> OrderTypes { get; set; }

        [DisplayName("Przypisz do pracownika")]
        public int EmployeeId { get; set; }
        public IEnumerable<SelectListItem> Empolyees { get; set; }

        [DisplayName("Wybierz samochód"), Required(ErrorMessage = "Wybór samochodu jest wymagant")]
        public int CarId { get; set; }
        public IEnumerable<SelectListItem> Cars { get; set; }

        [DisplayName("Status zlecenia"), Required(ErrorMessage = "Musisz wybrać status zlecenia")]
        public int OrderStatusId { get; set; }
        public IEnumerable<SelectListItem> OrderStatuses { get; set; }

        [DisplayName("Uszkodzenia")]
        public string RepairDescription { get; set; }

        public string ReturnUrl { get; set; }

        private readonly Data.Models.Order _order;

        public Create(Data.Models.Order order)
        {
            _order = order;
        }


        public Data.Models.Order ToOrder()
        {
            _order.CreateDate = DateTime.Now;
            _order.ModifyDate = DateTime.Now;
            _order.IsActive = true;
            _order.Customer = new Data.Models.Customer { Id = CustomerId };
            _order.OrderType = new Data.Models.OrderType { Id = OrderTypeId };
            _order.Employee = new Data.Models.Employee { Id = EmployeeId };
            _order.Car = new Data.Models.Car { Id = CarId };
            _order.OrderStatus = new Data.Models.OrderStatus { Id = OrderStatusId };
            _order.RepairDescription = RepairDescription;

            return _order;
        }

    }

}

CarService/CarService.Web/Controllers/Employee/EmployeeController.cs
using CarService.Web.Services.Address;
using CarService.Web.Services.Employee;
using CarService.Web.Services.Position;
using CarService.Web.Services.User;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web.Mvc;

namespace CarService.Web.Controllers.Employee
{
    public partial class EmployeeController : Controller
    {
        private readonly IPositionService _postionService;
        private readonly IUserService _userService;
        private readonly IEmployeeService _employeeService;
        private readonly IAddressService _addressService;
        
        public EmployeeController(IPositionService positionService,
            IUserService userService,
            IEmployeeService employeeService,
            IAddressService addressService)
        {
            _postionService = positionService;
            _userService = userService;
            _employeeService = employeeService;
            _addressService = addressService;
        }

        private int GetUserId()
        {
            var identity = (ClaimsIdentity)User.Identity;
            IEnumerable<Claim> claims = identity.Claims;
            return int.Parse(claims.Where(x => x.Type == "Id").Select(w => w.Value).FirstOrDefault());
        }
    }
}

CarService/CarService.Web/Controllers/Order/OrderController.cs
using CarService.Web.Services.Car;
using CarService.Web.Services.Cost;
using CarService.Web.Services.Employee;
using CarService.Web.Services.Order;
using System.Web.Mvc;

namespace CarService.Web.Controllers.Order
{
    public partial class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly ICarsService _carService;
        private readonly IEmployeeService _employeeService;
        private readonly ICostService _costService;

        public OrderController(IOrderService orderService,
            ICarsService carService,
            IEmployeeService employeeService,
            ICostService costService)
        {
            _orderService = orderService;
            _carService = carService;
            _employeeService = employeeService;
            _costService = costService;
        }
    }
}

CarService/CarService.Web/Views/Employee/Edit.cshtml
@model CarService.Web.ViewModels.Employee.EmployeeEdit
<div class="container">
    <div class="page-header"> @*style="color: #135bd3; >*@
        
        <div class="pull-right">
            <a href="@Url.Action("Schedule", "Employee", new { id = Model.Id})" class="btn btn-primary" style="font-size:17px; padding: 6px 6px 6px 6px; border-radius: 0px;">Moje naprawy</a>
        </div>
        <h3>Mój profil</h3>
        
    </div>
    @using (Html.BeginForm("Edit", "Employee"))
    {
        @Html.ValidationSummary()
        <div class="panel panel-body panel-default" style="border-radius: 0px;">
            <div class="row">
                <div class="col-md-5 col-md-push-1">
                    @Html.Partial("Employee/Partial/_Edit", Model)
                </div>
                <div class="col-md-7">
                    @Html.EditorFor(m => m.AddressEdit, "Shared/EditorTemplates/AddressEdit")
                </div>          
            </div>
            <button type="submit" class="btn btn-primary pull-right" style="border-radius:0px;">Zapisz</button>
        </div>
    }
</div>

CarService/CarService.Web/Views/Employee/Schedule.cshtml
@model IEnumerable<CarService.Web.ViewModels.Employee.Schedule>
<div class="container">
    @if (Model == null || !Model.Any())
    {
        <hr />
        <div class="alert alert-info text-center" style="margin-top:25px; border-radius: 0px;">Nie przypisano do ciebie żadnych napraw.</div>
    }
    @if (Model != null && Model.Any())
    {
        <div class="page-header">
            <h3>Twoja lista napraw</h3>
        </div>
        <table class="table table-striped table-bordered">
            <thead style="background-color: #135bd3; color:white">
                <tr>
                    <th>Nr zlecenia</th>
                    <th>Data utworzenia</th>
                    <th>Klient</th>
                    <th>Samochód</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td><a href="@Url.Action("Edit", "Order", new { id = item.OrderId, returnUrl = HttpContext.Current.Request.Url })">@item.OrderId</a></td>
                        <td>@item.CreateDate</td>
                        <td>@item.CustomerName</td>
                        <td>@item.Car</td>
                        <td>@item.OrderStatus</td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>

CarService/CarService.Web/Views/Employee/Search.cshtml
@model CarService.Web.ViewModels.Employee.EmployeeSearchItem
@using PagedList.Mvc;
<div class="container">
    <div class="page-header">
        <div class="pull-right">
            <a href="@Url.Action("Create", "Employee", new { returnUrl = HttpContext.Current.Request.Url })" class="btn btn-default" style="border-radius:0px; border-color: #808080; color:#140f11">
                <i class="fa fa-user-plus fa-fw"></i>Nowy pracownik
            </a>
        </div>
        <h3>Pracownicy</h3>
    </div>
    @using (Html.BeginForm("Search", "Employee"))
    {
        <div class="form-group row">
            <div class="col-md-2">
                @Html.LabelFor(m => m.Name, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control", @style = "border-radius: 0px" })
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m.Surname, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.Surname, new { @class = "form-control", @style = "border-radius: 0px" })
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m.Email, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control", @style = "border-radius: 0px" })
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m.PositionId, new { @class = "control-label" })
                @Html.DropDownListFor(m => m.PositionId, Model.Positions, "--Wybierz--", new { @class = "form-control", @style = "border-radius: 0px" })
            </div>
            <div class="col-md-2 col-md-offset-2" style="padding-top:25px;">
                <div class="pull-right">
                    <input type="submit" value="Szukaj" class="btn btn-primary" style="border-radius:0px; width:79px" />
                    <button type="button" id="clearBtn" class="btn btn-danger" style="border-radius:0px;">Wyczyść</button>
                </div>
            </div>
        </div>
        <div class="form-group">
            
        </div><br /><br />
    }
    <table class="table table-striped table-bordered" style="margin-top: -40px; margin-bottom:-10px;">
        <thead style="background-color: #135bd3; color:white">
            <tr>
                <th style="width:275px;">Imię i Nazwisko</th>
                <th style="width:200px;">Email</th>
                <th style="width:150px;">Telefon</th>
                <th style="width:200px;">Stanowisko</th>
                <th style="width:30px;">Naprawy</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.ResultItems)
            {
                <tr>
                    <td><a href="@Url.Action("View", "Employee", new { id = item.Id, returnUrl = HttpContext.Current.Request.Url })">@item.FullName</a></td>
                    <td>@item.Email</td>
                    <td>@item.Phone</td>
                    <td>@item.Position</td>
                    <td class="text-center"><strong>@item.CountOfTasks</strong></td>
                </tr>
            }
        </tbody>
    </table>
    @Html.PagedListPager(Model.ResultItems, page => Url.Action("Search", new { page }))
    @*<div id="TasksTable"></div>*@
</div>
<script>
    /*Czysczenie pól*/
    $(function () {
        $('#clearBtn').on('click', function () {
            $('#@Html.IdFor(x => x.Name)').val('');
            $('#@Html.IdFor(x => x.Surname)').val('');
            $('#@Html.IdFor(x => x.Email)').val('');
            $('#@Html.IdFor(x => x.PositionId)').val(null);
        });
    });

    /*Pobranie zadań*/
    @*$(function () {
        $.each('@Model.ResultItems', function (i, item) {
            $('#TasksBtn' + item.Id).on('click', function () {
            var employeeId = $(this).attr('data-id');
            var url = '@Url.Action("GetOrders", "Order", new { id = "--id--"})';
            alert('dziala');
            $.ajax({
                url: url.replace('--id--', employeeId),
                type: 'GET',
                dataType: 'json',
                success: function (data) {
                    console.log(data);
                    $('#TasksTable').html(
                        '<table class="table table-striped table-bordered">' +
                        '<thead style="background-color: #135bd3; color:white">' +
                        '<tr>' +
                        '<th style="width:30px;">Nr zl.</th>' +
                        '<th style="width:120px;">Klient</th>' +
                        '<th style="width:120px;">Samochód</th>' +
                        '<th style="width:120px;">Status</th>' +
                        '<th style="width:120px;">Typ</th>' +
                        '</tr>' +
                        '</thead>' +
                        '<tbody>')
                        $.each(data, function (i, item)
                        {
                            $('#TasksTable').find('tbody').append('<tr><td>' + item.Id + '</td>' +
                                '<td>' + item.Name + ' ' + item.Surname + '</td>' + 
                                '<td>' + item.Mark + ' ' + item.Model + '</td>' +
                                '<td>' + item.OrderStatus + '</td>' + 
                                '<td>' + item.OrderType +'</td>' +
                                '</tr>')
                        }) 
                        $('#TasksTable').append('</tbody>' +
                        '</table>');
                },
                error: function () {
                    console.log('Błąd pobierania danych');
                }
            });
            });
        })
    });*@

</script>

CarService/CarService.Web/Views/Employee/View.cshtml
@model CarService.Web.ViewModels.Employee.EmployeeEdit
<div class="container">
    <div class="page-header">
        @*<div class="pull-right">
            <a href="@Url.Action("Schedule", "Employee", new { id = Model.Id})" class="btn btn-primary" style="font-size:17px; padding: 6px 6px 6px 6px; border-radius: 0px;">Moje naprawy</a>
        </div>*@
        <h3>Profil: <b>@Model.Name @Model.Surname</b></h3>
    </div>
    @using (Html.BeginForm("View", "Employee"))
    {
        @Html.ValidationSummary()
        @Html.HiddenFor(m => m.EmployeeIsAdministrator)
        <div class="panel panel-body panel-default" style="border-radius: 0px;">
            <div class="row">
                <div class="col-md-5 col-md-push-1">
                    @Html.Partial("Employee/Partial/_Edit", Model)
                </div>
                <div class="col-md-7">
                    @Html.EditorFor(m => m.AddressEdit, "Shared/EditorTemplates/AddressEdit")
                    <div class="form-group row">
                        <div class="panel panel-default" style="border-radius: 0px; width: 540px">
                            <div class="panel-heading clearfix" style="padding: 6px 6px 6px 6px;">
                                <h4 class="panel-title text-center" style="padding:0px;"><b>Przypisane zlecenia</b></h4>
                            </div>
                            <div class="panel-body" style="padding: 0px; margin-bottom:-20px;">
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th style="width:30px; padding-top:4px; padding-bottom:4px;">Nr zl.</th>
                                            <th style="width:100px; padding-top:4px; padding-bottom:4px;">Klient</th>
                                            <th style="width:50px; padding-top:4px; padding-bottom:4px;">Status</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.OrderList)
                                        {
                                            <tr>
                                                <td style="padding-top:4px; padding-bottom:4px;"><a href="@Url.Action("Edit", "Order", new { id = item.Id, returnUrl = HttpContext.Current.Request.Url })">@item.Id</a></td>
                                                <td style="padding-top:4px; padding-bottom:4px;">@item.Customer</td>
                                                <td style="padding-top:4px; padding-bottom:4px;">@item.Status</td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-5 col-md-offset-1">
                    <div class="form-group row" style="border-radius:0px;">
                        <input type="checkbox" name="fancy-checkbox-primary" id="fancy-checkbox-primary" autocomplete="off" @(Model.EmployeeIsAdministrator ? "checked" : "") />
                        <div class="btn-group">
                            <label for="fancy-checkbox-primary" class="btn btn-primary" style="border-radius:0px; height:30px;">
                                <span class="glyphicon glyphicon-ok"></span>
                                <span></span>
                            </label>
                            <label for="fancy-checkbox-primary" class="btn btn-default active" style="border-radius:0px; height:30px; width:150px;">
                                Administrator
                            </label>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-md-offset-3">
                    <button type="submit" class="btn btn-primary pull-right" style="border-radius:0px;">Zapisz</button>
                </div>
            </div>
        </div>
    }
</div>
<script>
    $('#fancy-checkbox-primary').on('change', function () {
        if (this.checked)
        {
            $('#@Html.IdFor(m => m.EmployeeIsAdministrator)').val(true);
            console.log($('#@Html.IdFor(m => m.EmployeeIsAdministrator)').val())
        }
        else
        {
            $('#@Html.IdFor(m => m.EmployeeIsAdministrator)').val(false);
            console.log($('#@Html.IdFor(m => m.EmployeeIsAdministrator)').val())
        }
    });
</script>
<style>
    .form-group input[type="checkbox"] {
        display: none;
    }

        .form-group input[type="checkbox"] + .btn-group > label span {
            width: 15px;
            height: 30px;
        }

            .form-group input[type="checkbox"] + .btn-group > label span:first-child {
                display: none;
            }

            .form-group input[type="checkbox"] + .btn-group > label span:last-child {
                display: inline-block;
            }

        .form-group input[type="checkbox"]:checked + .btn-group > label span:first-child {
            display: inline-block;
        }

        .form-group input[type="checkbox"]:checked + .btn-group > label span:last-child {
            display: none;
        }
</style>