CarService/CarService.Web/ViewModels/Customer/CustomerEdit.cs
using CarService.Web.ViewModels.Shared.Address;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CarService.Web.ViewModels.Customer
{
    public class CustomerEdit
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Imię jest wymagane")]
        [DisplayName("Imię")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Nazwisko jest wymagane")]
        [DisplayName("Nazwisko")]
        public string Surname { get; set; }

        [Required(ErrorMessage = "Telefon jest wymagane")]
        [DisplayName("Telefon")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Adres e-mail jest wymagany")]
        [DisplayName("E-mail")]
        public string Email { get; set; }

        public AddressEdit AddressEdit { get; set; }

        public string ReturnUrl { get; set; }

        private readonly Data.Models.Customer _customer;

        public CustomerEdit(Data.Models.Customer customer)
        {
            _customer = customer ?? new Data.Models.Customer();

            if (customer != null && customer.Id != 0)
                Id = customer.Id;

            Name = customer.Name;
            Surname = customer.Surname;
            Phone = customer.Phone;
            Email = customer.Email;
            AddressEdit = new AddressEdit(customer.Address);
        }

        public Data.Models.Customer ToCustomer()
        {
            if (_customer.Id == 0)
            {
                _customer.CreateDate = DateTime.Now;
                _customer.IsActive = true;
            }

            _customer.ModifyDate = DateTime.Now;
            _customer.Name = Name;
            _customer.Surname = Surname;
            _customer.Phone = Phone;
            _customer.Email = Email;
            _customer.Address = _customer.Address == null ? AddressEdit.ToNewAddress() : AddressEdit.ToAddress();

            return _customer;
        }


    }
}

CarService/CarService.Web/ViewModels/Customer/CustomerListFilters.cs
using PagedList;
using System.Collections.Generic;
using System.ComponentModel;
using System.Web.Mvc;

namespace CarService.Web.ViewModels.Customer
{
    public class CustomerListFilters
    {
        [DisplayName("Nr klienta")]
        public int? CustomerId { get; set; }
        [DisplayName("Imię")]
        public string Name { get; set; }
        [DisplayName("Nazwisko")]
        public string Surname { get; set; }
        [DisplayName("Email")]
        public string Email { get; set; }
        [DisplayName("Sortowanie po")]
        public string SortedBy { get; set; }

        public IPagedList<ResultItem> ResultItems { get; set; }
        public IEnumerable<SelectListItem> SortedItems { get; set; }

        public CustomerListFilters()
        {
            SortedItems = new List<SelectListItem>
            {
                new SelectListItem { Value = "CustomerId ASC", Text = "Nr rosnąco" },
                new SelectListItem { Value = "CustomerId DESC", Text = "Nr malejąco" },
                new SelectListItem { Value = "Name ASC", Text = "Imię rosnąco" },
                new SelectListItem { Value = "NameDESC", Text = "Imię malejąco" },
                new SelectListItem { Value = "Surname ASC", Text = "Nazwisko rosnąco" },
                new SelectListItem { Value = "Surname DESC", Text = "Nazwisko malejąco" }
            };
        }
    }
}

CarService/CarService.Web/ViewModels/Customer/Edit.cs
using CarService.Web.ViewModels.Car;
using System.Collections.Generic;

namespace CarService.Web.ViewModels.Customer
{
    public class Edit
    {
        public CustomerEdit Customer { get; set; }
        public IEnumerable<CarItem> Cars { get; set; }
    }
}

CarService/CarService.Web/ViewModels/Customer/ResultItem.cs
namespace CarService.Web.ViewModels.Customer
{
    public class ResultItem
    {
        public int CustomerId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
    }
}

CarService/CarService.Web/ViewModels/Employee/Create.cs
using CarService.Web.Mvc.Other;
using CarService.Web.ViewModels.Shared.Address;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarService.Web.ViewModels.Employee
{
    public class Create : IValidatableObject
    {
        [DisplayName("Imię"), Required(ErrorMessage = "Imię jest wymagane")]
        public string Name { get; set; }

        [DisplayName("Nazwisko"), Required(ErrorMessage = "Nazwisko jest wymagane")]
        public string Surname { get; set; }

        [DisplayName("PESEL"), Required(ErrorMessage = "Pesel jest wymagany")]
        public string Pesel { get; set; }

        [Phone]
        [DisplayName("Telefon")]
        public string Phone { get; set; }

        [DisplayName("Email"), Required(ErrorMessage = "Email jest wymagany")]
        [EmailAddress]
        public string Email { get; set; }

        [DisplayName("Data urodzenia"), Required(ErrorMessage = "Data urodzenia jest wymagana")]
        [DataType(DataType.Date)]
        public DateTime BirthDate { get; set; }

        [DisplayName("Pensja")]
        public decimal? Salary { get; set; }

        [DisplayName("Stanowisko")]
        public int PositionId { get; set; }
        public IEnumerable<SelectListItem> Positions { get; set; }

        public bool IsAdministrator { get; set; }

        public AddressEdit AddressEdit { get; set; }

        public string ReturnUrl { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (IsValidBirthDay())
            {
                yield return new ValidationResult("Musisz mieć ukończone 18 lat", new[] { "BirthDate" });
            }
        }

        private bool IsValidBirthDay()
        {
            const long AgeOfAdult = 567648000000;

            var dt1900 = new DateTime(1900, 1, 1);
            var current = DateTime.Now;
            var spanCurrent = current - dt1900;
            var spanDateOfBirth = BirthDate - dt1900;

            var span = spanCurrent - spanDateOfBirth;
            return span.TotalMilliseconds < AgeOfAdult;
        }

        public Data.Models.User ToUser()
        {
            return new Data.Models.User
            {
                CreateDate = DateTime.Now,
                ModifyDate = DateTime.Now,
                IsActive = true,
                DateofBirth = BirthDate,
                Email = Email,
                Name = Name,
                Surname = Surname,
                Role_Id = IsAdministrator ? (int)Data.Enums.Role.Admin : (int)Data.Enums.Role.Employee,
                Password = Encrypt.EncryptPassword("qwerty1")
            };
        }

        public Data.Models.Employee ToEmployee(Data.Models.User user)
        {
            return new Data.Models.Employee
            {
                CreateDate = DateTime.Now,
                ModifyDate = DateTime.Now,
                IsActive = true,
                IsVerified = true,
                Name = Name,
                Surname = Surname,
                Pesel = Pesel,
                Phone = Phone,
                Position_Id = PositionId,
                Salary = Salary ?? 0,
                Address = AddressEdit.ToNewAddress(),
                User = user
            };
        }
    }
}

CarService/CarService.Web/ViewModels/Order/Create.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace CarService.Web.ViewModels.Order
{
    public class Create
    {
        [DisplayName("Wybierz klienta"), Required(ErrorMessage = "Wybór klienta jest wymagany")]
        public int CustomerId { get; set; }
        public IEnumerable<SelectListItem> Customers { get; set; }

        [DisplayName("Typ"), Required(ErrorMessage = "Typ zlecenia jest wymagany")]
        public int OrderTypeId { get; set; }
        public IEnumerable<SelectListItem> OrderTypes { get; set; }

        [DisplayName("Przypisz do pracownika")]
        public int EmployeeId { get; set; }
        public IEnumerable<SelectListItem> Empolyees { get; set; }

        [DisplayName("Wybierz samochód"), Required(ErrorMessage = "Wybór samochodu jest wymagant")]
        public int CarId { get; set; }
        public IEnumerable<SelectListItem> Cars { get; set; }

        [DisplayName("Status zlecenia"), Required(ErrorMessage = "Musisz wybrać status zlecenia")]
        public int OrderStatusId { get; set; }
        public IEnumerable<SelectListItem> OrderStatuses { get; set; }

        [DisplayName("Uszkodzenia")]
        public string RepairDescription { get; set; }

        public string ReturnUrl { get; set; }

        private readonly Data.Models.Order _order;

        public Create(Data.Models.Order order)
        {
            _order = order;
        }


        public Data.Models.Order ToOrder()
        {
            _order.CreateDate = DateTime.Now;
            _order.ModifyDate = DateTime.Now;
            _order.IsActive = true;
            _order.Customer = new Data.Models.Customer { Id = CustomerId };
            _order.OrderType = new Data.Models.OrderType { Id = OrderTypeId };
            _order.Employee = new Data.Models.Employee { Id = EmployeeId };
            _order.Car = new Data.Models.Car { Id = CarId };
            _order.OrderStatus = new Data.Models.OrderStatus { Id = OrderStatusId };
            _order.RepairDescription = RepairDescription;

            return _order;
        }

    }

}

CarService/CarService.Web/Controllers/Car/CarController.cs
using CarService.Web.Services.Car;
using CarService.Web.Services.Customer;
using System.Web.Mvc;

namespace CarService.Web.Controllers.Car
{
    public partial class CarController : Controller
    {
        private readonly ICustomerService _customerService;
        private readonly ICarsService _carService; 
        
        public CarController(ICustomerService customerService,
            ICarsService carService)
        {
            _customerService = customerService;
            _carService = carService;
        }
    }
}

CarService/CarService.Web/Controllers/Customer/CustomerController.cs
using CarService.Web.Services.Customer;
using System.Web.Mvc;

namespace CarService.Web.Controllers.Customer
{
    public partial class CustomerController : Controller
    {
        private readonly ICustomerService _customerService;

        public CustomerController(ICustomerService customerService)
        {
            _customerService = customerService;
        }
    }
}

CarService/CarService.Web/Views/Customer/Create.cshtml
@model CarService.Web.ViewModels.Customer.CustomerEdit
<div class="container">
    <div class="page-header">
        <h3>Dodawanie klienta</h3>
    </div>
    @using (Html.BeginForm("Create", "Customer", new { returnUrl = Model.ReturnUrl }))
    {
        @Html.ValidationSummary()
        <div class="panel panel-body panel-default" style="border-radius: 0px;">
            <div class="row">
                <div class="col-md-5 col-md-push-1">
                    @Html.Partial("Customer/Partial/_Edit", Model)
                </div>
                <div class="col-md-7">
                    @Html.EditorFor(m => m.AddressEdit, "Shared/EditorTemplates/AddressEdit")
                </div>
            </div>
            <a href="@Model.ReturnUrl" class="btn btn-danger pull-left" style="border-radius: 0px;">Anuluj</a>
            <button type="submit" class="btn btn-primary pull-right" style="border-radius:0px;">Zapisz</button>  
        </div>
    }
</div>

CarService/CarService.Web/Views/Customer/Edit.cshtml
@model CarService.Web.ViewModels.Customer.Edit
<div class="container">
    <div class="page-header">
        <h3>Nr klienta: @Model.Customer.Id - @string.Format("{0} {1}", Model.Customer.Name, Model.Customer.Surname)</h3>
    </div>
    @using (Html.BeginForm("Edit", "Customer", new { returnUrl = Model.Customer.ReturnUrl }))
    {
        @Html.ValidationSummary()
        <div class="panel panel-body panel-default" style="border-radius: 0px;">
            <div class="row">
                <div class="col-md-5 col-md-push-1">
                    @Html.Partial("Customer/Partial/_Edit", Model.Customer)
                </div>
                <div class="col-md-7">
                    @Html.EditorFor(m => m.Customer.AddressEdit, "Shared/EditorTemplates/AddressEdit")
                </div>
            </div>
            <a href="@Model.Customer.ReturnUrl" class="btn btn-danger pull-left" style="border-radius: 0px;">Anuluj</a>
            <button type="submit" class="btn btn-primary pull-right" style="border-radius:0px;">Zapisz</button>
        </div>
    }
    <div class="panel panel-default" style="border-radius: 0px;">
        <div class="panel-heading clearfix" style="padding: 6px 6px 6px 6px; border-radius:0px;">
            <h4 class="panel-title pull-left" style="padding-top:7.5px; ">Lista samochodów</h4>
            <div class="pull-right">
                <a href="@Url.Action("Create", "Car", new { id = Model.Customer.Id, returnUrl = HttpContext.Current.Request.Url})" class="btn btn-primary" style="border-radius: 0px; padding:4px 7px 2px 4px;">Nowy</a>
            </div>
        </div>
        <div class="panel-body" style="padding: 0; margin-bottom:-20px;">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Marka</th>
                        <th>Model</th>
                        <th>Silnik</th>
                        <th>Rok produkcji</th>
                        <th>Rejestracja</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Cars)
                    {
                        <tr>
                            <td>@item.Brand</td>
                            <td>@item.Model</td>
                            <td>@item.Engine cm<sup>3</sup></td>
                            <td>@item.ProductYear</td>
                            <td>@item.RegisterNumber</td>
                            @*<td class="text-center" style="width:50px;">
                                <a href="@Url.Action("Edit", "Customer", new { id = item.CustomerId, returnUrl = HttpContext.Current.Request.Url })" class="btn btn-sm btn-default" style="border-radius: 0px;"><span class="fa fa-fw fa-address-book"</a>
                            </td>*@
                        </tr>
                    }
                </tbody>
            </table>
            @*<div class="form-group row">
                <div class="col-md-3">
                </div>
                <div class="col-md-8">
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-3">
                </div>
                <div class="col-md-6">
                    <div class="input-group">
                    </div>
                </div>
            </div>*@
        </div>
    </div>
</div>
<script>
    $('#@Html.IdFor(m => m.Customer.Name)').prop('disabled', true);
    $('#@Html.IdFor(m => m.Customer.Surname)').prop('disabled', true);
    $('#@Html.IdFor(m => m.Customer.Phone)').prop('disabled', true);
    $('#@Html.IdFor(m => m.Customer.Email)').prop('disabled', true);
    $('#@Html.IdFor(m => m.Customer.AddressEdit.City)').prop('disabled', true);
    $('#@Html.IdFor(m => m.Customer.AddressEdit.FlatNumber)').prop('disabled', true);
    $('#@Html.IdFor(m => m.Customer.AddressEdit.PostalCode)').prop('disabled', true);
    $('#@Html.IdFor(m => m.Customer.AddressEdit.Street)').prop('disabled', true);
</script>

CarService/CarService.Web/Views/Customer/List.cshtml
@model CarService.Web.ViewModels.Customer.CustomerListFilters
@using PagedList.Mvc;
<div class="container">
    <div class="page-header">
        <div class="pull-right">
            <a href="@Url.Action("Create", "Customer", new { returnUrl = HttpContext.Current.Request.Url})" class="btn btn-default" style="border-radius:0px; border-color: black; color:black">
                <i class="fa fa-male fa-fw"></i>Nowy klient
            </a>
        </div>
        <h3>Lista klientów</h3>
    </div>
    @*<div class="panel panel-info panel-body" style="border-radius: 0px;">
            <div class="form-group row"></div>
        </div>*@
    @using (Html.BeginForm("List", "Customer"))
    {
        <div class="form-group row">
            <div class="col-md-2">
                @Html.LabelFor(m => m.CustomerId, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.CustomerId, new { @class = "form-control", @style = "border-radius: 0px" })
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m.Email, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control", @style = "border-radius: 0px" })
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m.Name, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control", @style = "border-radius: 0px" })
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m.Surname, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.Surname, new { @class = "form-control", @style = "border-radius: 0px" })
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m.SortedBy, new { @class = "control-label" })
                @Html.DropDownListFor(m => m.SortedBy, Model.SortedItems, "", new { @class = "form-control", @style = "border-radius: 0px;" })
            </div>
        </div>
        <div class="form-group">
            <div class="pull-right">
                <input type="submit" value="Szukaj" class="btn btn-primary" style="border-radius:0px; width:79px" />
                <button type="button" id="clearBtn" class="btn btn-danger" style="border-radius:0px;">Wyczyść</button>
            </div>
        </div><br /><br />
    }
    <table class="table table-striped table-bordered">
        <thead style="background-color: #135bd3; color:white">
            <tr>
                <th style="width:85px;">Nr klienta</th>
                <th style="width:150px;">Imię</th>
                <th style="width:150px;">Nazwisko</th>
                <th style="width:200px;">Email</th>
                <th style="width:120px;">Telefon</th>
                <th>Adres</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.ResultItems)
            {
                <tr>
                    <td>@item.CustomerId</td>
                    <td>@item.Name</td>
                    <td>@item.Surname</td>
                    <td>@item.Email</td>
                    <td>@item.Phone</td>
                    <td>@item.Address</td>
                    <td class="text-center" style="width:50px;">
                        <a href="@Url.Action("Edit", "Customer", new { id = item.CustomerId, returnUrl = HttpContext.Current.Request.Url })" class="btn btn-sm btn-default" style="border-radius: 0px;"><span class="fa fa-fw fa-address-book"</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    @Html.PagedListPager(Model.ResultItems, page => Url.Action("List", new { page }))
</div>
<script>
    $(function () {
        $('#clearBtn').on('click', function () {
            $('#@Html.IdFor(x => x.CustomerId)').val('');
            $('#@Html.IdFor(x => x.Name)').val('');
            $('#@Html.IdFor(x => x.Surname)').val('');
            $('#@Html.IdFor(x => x.Email)').val('');
            $('#@Html.IdFor(x => x.SortedBy)').val('');
        });
    });

</script>